### PR TITLE
Create new Meetups & .NET Virtual User Group Pages

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Create new "meetups" page combining find/host/resources and new virtual user group page. Update routes and navigation as well. Added redirects where needed

Still needed:

* [x] Grammar Review
* [x] New icons for new sections
* [x] Update CSS in meetups page

New Meetups Page -> (combines host/find):
image
image

New Virtual User Group Page
image
image
image

### CODE REVIEW

**Comment by AlexHedley** [comment]
There's a few ways to get a full screenshot if that'll save time instead of splitting it:

https://css-tricks.com/full-page-screenshots-browsers/

**Comment by clairernovotny** [comment]
@dotnet-foundation/marketing any feedback on this?

**Comment by ddskier** [comment]
I think it looks great. Two pieces of feedback: 1) The button in "Meetup Resources" says "Browser Resources" instead of "Browse Resources". 2) I would move "Past Events" to the end.

All in all, looks very good.

**Comment by isaacrlevin** [comment]
@clairernovotny should this be linked to/promoted from the "Get Involved" Page?

**Comment by clairernovotny** [comment]
@isaacrlevin yes

**Comment by isaacrlevin** [comment]
@jamesmontemagno any issue with me adding that to this PR?

**Comment by jamesmontemagno** [comment]
Feel free to add edits to it. It also needs some icons/graphics made for each swimlane...

**Comment by isaacrlevin** [comment]
@clairernovotny proposal to move the contents of community/get-involved to community and list issues and call out meetups. Will provide mockup

**Comment by isaacrlevin** [comment]
This is what the new community page would look like

screenshot-localhost_5080-2020 08 05-10_28_19

cc @clairernovotny @BethMassi

**Comment by clairernovotny** [comment]
I'm not a design person but my gut is telling me that there's too much on this page and too much scrolling. Like we need some other kind of UX paradigm but I'm not sure what.

**Comment by isaacrlevin** [comment]
We could remove the D&I section and link to the CoC in the footer?

**Comment by jamesmontemagno** [comment]
I think that the new Community page should be a separate PR than this one. So we can push this out first.

I have updated new icons. Ready to go on my side.

**Pull request merged**
