### PR TITLE
Add myself as speaker

### PR DESCRIPTION
**Pull request by matkoch**

### CODE REVIEW

**Review by shawnwildermuth — CHANGES_REQUESTED** [review]
Please remove Build Automation, it's not a topic we have our topic list.

**Comment by matkoch** [comment]
Wouldn't it be good to add then? I mean i see way more talks about build automation than I see about watchOS for instance, and there are multiple tools in that space as well.

**Comment by matkoch** [comment]
Same goes btw for Testing. Such a wide field and particularly popular for talks and workshops of various kind. I've never seen a NuGet talk though :) Can we extend this please?

**Comment by shawnwildermuth** [comment]
You can recommend them as an Issue, but in order to allow for the PR to go through it has to be one of the approved topics right now.

**Comment by matkoch** [comment]
done

**Comment by matkoch** [comment]
@shawnwildermuth where should the issue be filed? the templates for this repo don't fit.

**Review by shawnwildermuth — APPROVED** [review]

**Comment by shawnwildermuth** [comment]
If you look at the 'new issue', it says a 'blank issue' on the bottom (below the two big choices).

**Pull request merged**
