### PR TITLE
fix projects spotlight

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/dotnet-foundation/website/issues/1029

### CODE REVIEW

**Comment by isaacrlevin** [comment]
@Arhell what are you trying to do here?

**Comment by Arhell** [comment]
> @Arhell what are you trying to do here?

fix this https://dotnetfoundation.org/projects/spotlight#PresetProjects

**Comment by Arhell** [comment]
Preview
https://jolly-grass-05beb181e-1030.westus2.azurestaticapps.net/projects/spotlight#PresetProjects

**Comment by isaacrlevin** [comment]
Ah ok, would be good to have them sorted regardless of case

**Comment by Arhell** [comment]
> Ah ok, would be good to have them sorted regardless of case

I do not mind, but I will do it in the next PR
Now the task was to correct the html

**Review by isaacrlevin — APPROVED** [review]

**Pull request merged**
