### PR TITLE
Task/Fixed wrong video bug

### PR DESCRIPTION
**Pull request by blackinsure**
Noticed a wrong video on my page. Just removed. Please merge. Thanks

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1181) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1181) before we can accept your contribution.<br/><br/>:x: blackinsure [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1181)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=1181) it.</sub>

**Review by BillWagner — APPROVED** [review]
This LGTM.

Thanks @blackinsure

**Comment by BillWagner** [comment]
hi @blackinsure Once you sign the CLA, I'll merge this.

**Comment by BillWagner** [comment]
hi @blackinsure 

this PR might be redundant with #1182. That PR publishes this year's videos. I added a link to the video you made earlier today.

**Review by Arhell — APPROVED** [review]

**Pull request closed without merging**
