### PR TITLE
Fixed #951

### LINKED ISSUE #951: Disable blog reading for local development
We should be able to disable the reading of blogs when developing and previewing locally for a faster rebuild loop. This can be accomplished pretty easily with a new setting. I’ll submit a PR for this soon, so this is just a placeholder issue.

cc @NicoleAbuhakmeh

### PR DESCRIPTION
**Pull request by NikoMix**
Following the implementation of SuppressSpeakers and SuppressProjects I've added Suppression Toggles for retrieving Speaker Blog Entries, Images and Geo Locations to speed up the build process.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
cc @daveaglick

**Comment by daveaglick** [comment]
Looks fine to me, :shipit:!

**Review by daveaglick — APPROVED** [review]

**Comment by Arhell** [comment]
@NikoMix 
Hello, your branch seems to be merged, but I can't merge it, you can close it or make a new one

**Comment by NikoMix** [comment]
@Arhell weird.... it seamed to be merged into the codebase. I'll go ahead and close this.

**Comment by Arhell** [comment]
> @Arhell weird.... it seamed to be merged into the codebase. I'll go ahead and close this.

Some kind of bug is possible, the first time I encounter this

**Pull request closed without merging**
