### PR TITLE
update cookieconsent

### PR DESCRIPTION
**Pull request by Arhell**

### CODE REVIEW

**Comment by Arhell** [comment]
fix console error
https://github.com/dotnet-foundation/website/issues/1046

**Comment by Arhell** [comment]
cc @rprouse

**Comment by Arhell** [comment]
cc @rprouse
This PR fixes banner, screenshot above.
Due to the change here https://github.com/dotnet-foundation/website/commit/fb22dfded3c71db205ca00331392a92df74d7788#diff-a21310a56d688123443e6e10f0d05edd52e0bcf152a83123ab631d5c265

cookie-consent.3.0.0.js

When correcting quotes, this script stopped working.
I returned it to its previous state when I was working.

**Review by rprouse — APPROVED** [review]
Good catch. Missed this in the last PR.

**Pull request merged**
