### PR TITLE
Create sarah-dutkiewicz.md

### PR DESCRIPTION
**Pull request by sadukie**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=544) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=544) before we can accept your contribution.<br/><br/>:x: sadukie [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=544)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=544) it.</sub>

**Comment by clairernovotny** [comment]
Looks like one of the topic tag's isn't on the list, though I agree that one should be there @JaySing @daveaglick 

```
Error: Document contains non-approved topic(s): User Experience (ValidateSpeakerTopics)
```

**Comment by daveaglick** [comment]
@sadukie Do you mind adding the "User Experience" topic here as part of your PR: https://github.com/dotnet-foundation/website/blob/master/Analyzers/ValidateSpeakerTopics.cs - that way we can track it with your profile and the build validation will pass.

**Comment by daveaglick** [comment]
Nevermind, I got it :)

**Review by daveaglick — APPROVED** [review]

**Pull request merged**
