### PR TITLE
Need updates for Codegarden

### PR DESCRIPTION
**Pull request by BethMassi**
@poornimanayar can you update this with a link to the recordings from the event? I will send this out on June 30.

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by poornimanayar** [comment]
Hi @BethMassi ,

The playlist of recordings is available at https://www.youtube.com/playlist?list=PLG_nqaT-rbpx6wIDr5ufUlbHkg6qB3sxH 

More recordings will be added next week.

Poornima

**Comment by BethMassi** [comment]
Great. Can you update the copy to what you want to say? You can just suggest edits to this pull request. Thank you!

**Review by Arhell — APPROVED** [review]

**Comment by poornimanayar** [comment]
Hi @BethMassi ,

Let me get back to you on this one. I need someone at the Umbraco  HQ to amend the content for me. Give me a day and I will get back to you on this one.

Poornima

**Comment by poornimanayar** [comment]
Hi @BethMassi ,

Here is the updated content, Do u want me to raise this as a PR in the other repo?

Umbraco Codegarden 2021 was a virtual tech conference to remember! :fire:

Earlier in June, Umbraco held the very first virtual Codegarden, and it saw over 2200 attendees enjoy 3 days of updates, discussions and ideas from Umbraco developers, the Umbraco community, and industry experts. 

Talks and sessions are being uploaded to the [Umbraco YouTube channel](https://www.youtube.com/umbracohq) already, but here’s a few to get you started: 

[Scott Hunter, .NET Director of Program Management  - Future of application development with .NET](https://www.youtube.com/watch?v=Btvm-x5BRYg&list=PLG_nqaT-rbpx6wIDr5ufUlbHkg6qB3sxH&index=20)
[Bjarke Berg and Elitsa Marinovska, Umbraco Development Team - Umbraco 9 - the next major version](https://www.youtube.com/watch?v=a-NFlIKO1TQ&list=PLG_nqaT-rbpx6wIDr5ufUlbHkg6qB3sxH&index=19)
[Kim Sneum Madsen, Umbraco Chief Friend Maker (CEO) -   Opening keynote](https://www.youtube.com/watch?v=D_nLL-O2YIM&list=PLG_nqaT-rbpx6wIDr5ufUlbHkg6qB3sxH)

Sad that you missed out on all the bits in between? Then come and join us for Codegarden 2022 next summer!
For all the info on Codegarden 2022 when it comes, make sure you’re following us on [Twitter](https://twitter.com/umbraco?lang=da) and [LinkedIn](https://www.linkedin.com/company/umbraco), or [sign up for our newsletter](https://umbraco.activehosted.com/f/2) to get updates straight into your inbox.

**Comment by BethMassi** [comment]
This is great @poornimanayar. I can add it in. No problem!

**Pull request merged**
