### PR TITLE
update Projects links

### PR DESCRIPTION
**Pull request by Arhell**
issue #6
added new links and updated mobile

### CODE REVIEW

**Comment by clairernovotny** [comment]
These shouldn’t be in the main nav area.

**Comment by Arhell** [comment]
Hi @clairernovotny 
Do you mean here?
4c3cd5317c

If you insert them all there, then there will be not enough space, can create a separate menu?

**Comment by clairernovotny** [comment]
No, I'm suggesting they go here instead of on the menu at all: https://github.com/dotnet-foundation/website/tree/master/input/projects/data

**Comment by Arhell** [comment]
@clairernovotny  Thanks!
Added new pages.
There is a minimum of information.

**Pull request merged**
