### PR TITLE
Upgrade project to .NET 5

### PR DESCRIPTION
**Pull request by MoienTajik**
- Upgraded project to .NET 5
- Removed unused namespaces
- Replaced class names with keywords for common types (ex: String -> string, Char -> char)
- Updated NuGet packages
- Removed commented sections in .csproj

### CODE REVIEW

**Comment by MoienTajik** [comment]
The .NET version needs to be updated on the CI server, so the pipeline will succeed.

**Comment by daveaglick** [comment]
Is there a particular benefit you're hoping to gain by updating to .NET 5 at this point, or mainly doing the update as a best practice?

**Comment by MoienTajik** [comment]
I just did this as a best practice + a little code cleanup in the project.

**Comment by clairernovotny** [comment]
@daveaglick I defer to your judgement on this.

**Comment by clairernovotny** [comment]
@MoienTajik You also need to bump the .NET SDK version here: https://github.com/dotnet-foundation/website/blob/master/.github/workflows/azure-static-web-apps-jolly-grass-05beb181e.yml#L28

**Comment by daveaglick** [comment]
Cool - I'll take it for a spin early next week. Thanks!

**Review by Arhell — APPROVED** [review]

**Comment by clairernovotny** [comment]
@daveaglick any thoughts?

**Comment by daveaglick** [comment]
Yeah, actually - I had been stalling on this one thinking there would be gremlins, but I recently ported Discover .NET to .NET 5 and other than some additional analyzer errors that needed to be adjusted everything worked totally fine. I'll give this an approval - might speed up builds a bit too.

**Review by daveaglick — APPROVED** [review]

**Pull request merged**
