### PR TITLE
Added Placeholders for 2021 Campaign

### PR DESCRIPTION
**Pull request by NicoleAbuhakmeh**
Added 2021 campaign folder with current candidates. Also added placeholder for 2021 candidates asset folder. Also modified the candidates page to pull from the 2021 candidates folder.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=950) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=950) before we can accept your contribution.<br/><br/>:x: NicoleAbuhakmeh [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=950)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=950) it.</sub>

**Comment by NicoleAbuhakmeh** [comment]
Adding @daveaglick because he's currently updating the site to the latest version of Statiq and is making some changes.

**Comment by daveaglick** [comment]
Changes look fine to me - #949 looks like it was actually already merged (thanks @clairernovotny!) so the version update is already in the code here. Don’t see anything that would cause problems under the new version 👍

**Review by Arhell — APPROVED** [review]

**Comment by NicoleAbuhakmeh** [comment]
deploying website with changes for Election 2021

**Pull request merged**
