### PR TITLE
DNN Project spotlight

### PR DESCRIPTION
**Pull request by isaacrlevin**
Adding placeholder for DNN Project Spotlight

### CODE REVIEW

**Comment by isaacrlevin** [comment]
Test Site

https://purple-beach-0c9a3421e.azurestaticapps.net/projects/spotlight

**Comment by isaacrlevin** [comment]
@claire this is G2G, when you merge this in, please delete

azure-static-web-apps-purple-beach-0c9a3421e.yml

and this dir
website/input/projects/spotlight/

This PR also resolves #361 

This should also coincide with the latest newsletter

**Comment by clairernovotny** [comment]
@isaacrlevin I see conflicts in this PR, can you please resolve and then I can merge? If you remove the two files from your PR then it should just flow through.

**Comment by isaacrlevin** [comment]
@clairernovotny should be good now, let me verify the pr environment and I will tag you to merge

**Comment by isaacrlevin** [comment]
Lgtm!!!

**Comment by isaacrlevin** [comment]
One comment, why do PRs not trigger a deployment for checking?

**Comment by clairernovotny** [comment]
They don't from forks. I can give you rights to push to branches on this repo and it'll trigger a staging environment.

**Comment by isaacrlevin** [comment]
Cool, going forward I can add project spotlight content via a branch in this repo. Btw you can merge this

**Pull request merged**
