### PR TITLE
Update outdated Project Page on the Windows Community Toolkit

### PR DESCRIPTION
**Pull request by michael-hawker**
We had changed our name and project leader a couple of times since this was last updated, this is all current now. Thanks!

### CODE REVIEW

**Comment by michael-hawker** [comment]
QQ: I noticed [this old blog post](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/welcome-windows-template-studio.md) will now have outdated links, should that be updated with an 'Edit' call out or something on it or do you ignore old posts?

Or should I leave the file name the same for the URL but just change the content? What does the index page use (I assume it's auto-generated)?

**Comment by clairernovotny** [comment]
@daveaglick why are we seeing validation warnings here? `https://dotnetfoundation.org/projects/uwpcommunitytoolkit` is correct.

**Comment by clairernovotny** [comment]
Oh, nm, it's a rename

**Review by clairernovotny — CHANGES_REQUESTED** [review]
Can you please update the old url's (called out in the validation) and add an entry to the `input/routes.json` for a redirect so that any old links still work?

**Comment by michael-hawker** [comment]
Sorry @clairernovotny didn't get the notification. We should be good now?

**Comment by clairernovotny** [comment]
Yes, should be similar to the others in that file.

**Comment by michael-hawker** [comment]
@clairernovotny think we're good now? Not sure why GitHub didn't do a `git mv`, but other than that...

**Pull request merged**
