### PR TITLE
min svg favicon

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/dotnet-foundation/website/issues/1106

### CODE REVIEW

**Comment by rprouse** [comment]
Any purpose other than size?

**Comment by Arhell** [comment]
> Any purpose other than size?

just the size so that the content loads a fraction of a second faster

**Comment by Arhell** [comment]
@rprouse add new icon

**Comment by Arhell** [comment]
cc @rprouse

**Comment by Arhell** [comment]
cc @isaacrlevin

**Pull request merged**
