### PR TITLE
Add HTML5 form validation for speaker inputs

### PR DESCRIPTION
**Pull request by SeanKilleen**
CC @daveaglick 

This is a work in progress. Figured I would try to provide HTML5 validation to prevent build issues later on.

* [x] Add url input types
* [x] Add required attribute for name
* [x] Add Example URLs and display them
* [x] Add some regex validations and utilize them

## Regex Validation Tests (for reference)

NOTE: I copied directly from this regex test and the only change I made after that was using `\\` for the escape in C#.

* Twitter: https://regex101.com/r/LsRovM/1
* GitHub: https://regex101.com/r/FICmFg/1
* LinkedIn: https://regex101.com/r/IlrLEM/1
* Twitch: https://regex101.com/r/D1Kxdu/1
* StackOverflow: https://regex101.com/r/0OHcSZ/1

### CODE REVIEW

**Comment by SeanKilleen** [comment]
I was thinking it would be good to go through the `SpeakerLinkAttribute` items and specify two additional data points -- an example URL and a regex for validation. We could then pipe those into the HTML label and a pattern regex matcher in the HTML. This would ensure that folks who submitted the form would get some actionable feedback and that those submissions that made it through would be less likely to have build issues.

For now, this could be merged as-is or we could take it to the next step as described above, but at first glance I had a little bit of difficulty finding where the `SpeakerLinkAttribute` items were.

**Comment by daveaglick** [comment]
> I was thinking it would be good to go through the SpeakerLinkAttribute items and specify two additional data points -- an example URL and a regex for validation. We could then pipe those into the HTML label and a pattern regex matcher in the HTML.

Fantastic idea! The `SpeakerLinkAttribute` is at:
https://github.com/dotnet-foundation/website/blob/master/SpeakerLinkAttribute.cs

And it's applied to items in the global keys file at:
https://github.com/dotnet-foundation/website/blob/master/SiteKeys.cs

(It's certainly debatable whether the speaker link keys should maybe be in a different file for better organization)

**Comment by daveaglick** [comment]
That was fast :)

I came back to merge this after checking locally and you're already working on the enhancement! I'm assuming that's a WIP now? If so, I'll hold off on the merge until the speaker link part is done.

**Comment by SeanKilleen** [comment]
@daveaglick haha yep, I jumped right into it. Figured we might as well go all in. Thanks!

**Comment by SeanKilleen** [comment]
@daveaglick OK, I think this is ready for you to check. I haven't done all the inputs yet due to time constraints but this should give us a running start that I (or others) can build on.

**Comment by daveaglick** [comment]
This is fantastic, should really help reduce mistakes before they even get to the PR stage. Checking locally and then I'll merge. We can continue to build on it as we go.

**Review by daveaglick — APPROVED** [review]

**Pull request merged**
