### PR TITLE
Adding Survey Placeholder

### PR DESCRIPTION
**Pull request by isaacrlevin**
Adding Survey Placeholder

cc @BethMassi

### CODE REVIEW

**Comment by BethMassi** [comment]
Can we make the "Take the survey" link on the homepage a pink button? You can't see it right now.

**Comment by isaacrlevin** [comment]
> Can we make the "Take the survey" link on the homepage a pink button? You can't see it right now.

Take a look now

**Comment by BethMassi** [comment]
I just updated the rules copy. Button looks WAY better.

**Comment by ddskier** [comment]
All of this looks great. Website looks good - do we want to be more specific about the survey? For example, something like "help us improve the .NET Foundation and take our survey" or is that too long? Also, I took the survey (you can delete my response) and that looks great too.

**Comment by BethMassi** [comment]
@ddskier I can update the first page of the survey in SurveyMonkey. Currently it says this. Let me know what you think it should say: 

Thank you for participating in our survey. Your feedback is important to the .NET Foundation. It will help us understand our community needs better and prioritize the work that we do. This survey will stay open until March 31, 2021 after which the results will be made public. 

Complete this survey and you can enter to win a $250 gift certificate. Multiple winners! See the official prize giveaway rules for details.

**Comment by ddskier** [comment]
@BethMassi I think your survey text looks great. No changes.

**Comment by ddskier** [comment]
Changing "the" to "our" is a much better solution than my long-winded suggestion. :)

**Comment by BethMassi** [comment]
@isaacrlevin can you push these live on Monday evening / Tuesday early AM?

**Comment by isaacrlevin** [comment]
@clairernovotny since she has the merge power

**Pull request merged**
