### PR TITLE
css refactor

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/dotnet-foundation/website/issues/922

### CODE REVIEW

**Comment by Arhell** [comment]
updated css to scss to make it easier and more convenient to edit and add styles
cc @clairernovotny

**Comment by clairernovotny** [comment]
@shawnwildermuth @daveaglick

**Comment by Arhell** [comment]
cc @daveaglick

**Comment by daveaglick** [comment]
It looks fine to me from a generator standpoint - I think the question is, does the new CSS work with the site? If it does, and if the Foundation is on board with whatever style changes are in here, I don't see any problem.

**Comment by Arhell** [comment]
I just converted the css to sass using the converter https://css2sass.herokuapp.com/

I did not find any changes, but it will be a little more convenient to work

**Review by shawnwildermuth — APPROVED** [review]

**Pull request merged**
