### PR TITLE
Adding Help Wanted Issues from Foundation GitHub Repos

### PR DESCRIPTION
**Pull request by isaacrlevin**
Adding New Section to Community Page to broadcast "Help Wanted" Issues in Foundation Repos

### CODE REVIEW

**Comment by clairernovotny** [comment]
Does this break rss generation? The build generated an xml file that the function at api/rss served. We can’t change the rss function name as it’d break existing subscribers.

**Comment by isaacrlevin** [comment]
I would love to test just that, but
The content server has rejected the request with: BadRequest
Reason: This static site already has the maximum number of environments (1). Please remove one and try again.

**Comment by daveaglick** [comment]
FWIW, Statiq Web 1.0.0-alpha.20 shipped last night which includes a new `ExcludedPaths` setting that can be set from the CLI (`-s ExcludedPaths=api`, the excluded paths are always assumed to be under `input`), in the bootstrapper, or in a configuration file.

I'm not sure that's going to be quite what's needed here though. If the Static Web Apps API is set to `output/api` and we're relying on Statiq to generate the content for that, then excluding the input equivalent of `input/api` will also prevent the RSS feed output. If it's enough to _just_ exclude `api/node_modules` then you could probably do that (again, because the `ExcludedPaths` are implicitly under `input` this actually excludes `input/api/node_modules`).

**Comment by isaacrlevin** [comment]
This is one of those things I just need to test. I am going to create a web app against a fork just to see how the redirects work

**Comment by isaacrlevin** [comment]
Would there be any concerns with just making this an external function that the static app calls? Based on what I'm seeing we really can't do what we need in one project.

**Comment by clairernovotny** [comment]
How is that function protected from abuse? when served from the same site, doesn't need any CORS headers, etc.

**Comment by isaacrlevin** [comment]
Well you would have to set-up CORs on the Azure Function, same as any public api

**Comment by clairernovotny** [comment]
Why? From it's own domain it's same origin?

**Comment by clairernovotny** [comment]
Two things:

1. This doesn't seem to be working currently...it's not picking up the function in api/issues. You can see in the staging site that there's a 404 on that call. (/api/rss works there).
2. I'd prefer not to commit the community.js file. That's a generated asset. We should have a BeforeBuild target [here](https://github.com/dotnet-foundation/website/blob/master/Generator.csproj#L36) that invokes whatever is needed to run the build. The ASP.NET Core SPA templates do this, so we can crib from those...

**Comment by isaacrlevin** [comment]
What do you mean community.js is a generated asset? I followed a similar pattern as home.js which is commited

**Comment by clairernovotny** [comment]
not community.js, issue.js

**Comment by isaacrlevin** [comment]
Got it. Does it make sense to do this in the action or in the build step. I suck at MSBuild so would need some help on setting that up. Debugging will be a problem though as you can't have js and ts Azure Functions together in the same workspace

**Comment by clairernovotny** [comment]
for now, it can probably be the actions build step. though eventually better to do it in msbuild. would be interesting to get the functions runtime working here to be able to debug everything locally.

**Comment by isaacrlevin** [comment]
You would have to update the rss function to be TS, than you transpile both and move both to the api folder

**Comment by clairernovotny** [comment]
It's a really simple function, it can be typescript. I was going for quick-and-dirty :)

**Comment by clairernovotny** [comment]
Looks good. Last thing to verify -- after you do the steps with npm & typescript, are there artifacts that should be added to the .gitignore so they're not accidently added?

**Comment by isaacrlevin** [comment]
The only thing that gets put in input/api is the transpiled js file. Everything else is already there so I think we are good

**Comment by clairernovotny** [comment]
Is that tile in the ignore list?

**Comment by isaacrlevin** [comment]
Tile?

**Comment by clairernovotny** [comment]
Sorry, typo, "file". Just want to make sure that locally when running `dotnet run` to generate things, that there aren't any files that'll show up as needing to be added.

**Comment by isaacrlevin** [comment]
dotnet run and preview runs without issue, not sure if that is what you are asking. because the functions code is outside of the input folder, the only thing that changes in input is that we put the transpiled js in the input/api folder

**Comment by clairernovotny** [comment]
Right...which is why that transpiled filename needs to be added to the `.gitignore` so it doesn't get checked in.

**Pull request merged**
