### PR TITLE
2021 campaign - Frank Odoom

### PR DESCRIPTION
**Pull request by frankodoom**
My Campaign submission.

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by Arhell** [comment]
Please change the branch
dotnet-foundation:main to 2021-campaign github ui

**Comment by frankodoom** [comment]
> Please change the branch
> dotnet-foundation:main to 2021-campaign github ui

changed the base to 2021-campaign

**Review by shawnwildermuth — CHANGES_REQUESTED** [review]
Please change Twitter to URL.  Also, you might want to include an image.

**Comment by frankodoom** [comment]
> Please change Twitter to URL. Also, you might want to include an image.

noted @shawnwildermuth

**Review by shawnwildermuth — CHANGES_REQUESTED** [review]
Sorry, please use the entire twitter link, not just the handle. Also, the image doesn't seem to exist in your commit.

**Review by shawnwildermuth — APPROVED** [review]

**Pull request merged**
