### PR TITLE
board of directors ui update

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/dotnet-foundation/website/issues/846
after fix

### CODE REVIEW

**Comment by rstm-sf** [comment]
Hi, I don't understand in design, but I'm more used to it when there is some kind of character separator :)

Maybe this is also welcomed and just a matter of habit

**Comment by Arhell** [comment]
> Hi, I don't understand in design, but I'm more used to it when there is some kind of character separator :)
> 
> Maybe this is also welcomed and just a matter of habit

add "-"
https://jolly-grass-05beb181e-847.westus2.azurestaticapps.net/about/board-of-directors

**Comment by rstm-sf** [comment]
> 
> 
> > Hi, I don't understand in design, but I'm more used to it when there is some kind of character separator :)
> > Maybe this is also welcomed and just a matter of habit
> 
> add "-"
> https://jolly-grass-05beb181e-847.westus2.azurestaticapps.net/about/board-of-directors

Thank you!

I apologize for my caprice, maybe just to move to a new line (or just refuse this information altogether -- it can change and we need to keep track of it)?

The character is located slightly below, as it seems to me
image

**Comment by Arhell** [comment]
> > > Hi, I don't understand in design, but I'm more used to it when there is some kind of character separator :)
> > > Maybe this is also welcomed and just a matter of habit
> > 
> > 
> > add "-"
> > https://jolly-grass-05beb181e-847.westus2.azurestaticapps.net/about/board-of-directors
> 
> Thank you!
> 
> I apologize for my caprice, maybe just to move to a new line (or just refuse this information altogether -- it can change and we need to keep track of it)?
> 
> The character is located slightly below, as it seems to me
> image

https://jolly-grass-05beb181e-847.westus2.azurestaticapps.net/about/board-of-directors
Thank you, I corrected it, I have no right to delete information, I don’t accept such decisions, I just slightly corrected the ui

**Comment by rstm-sf** [comment]
Ok, thank you!

**Pull request merged**
