### PR TITLE
2022 Campaign

### PR DESCRIPTION
**Pull request by isaacrlevin**
@BillWagner looks like there is no nominating committee page for 2022. Can you work on that in the branch?

### CODE REVIEW

**Comment by BillWagner** [comment]
will do!

**Comment by shawnwildermuth** [comment]
Looks like we have missing images.

**Review by Arhell — APPROVED** [review]

**Comment by isaacrlevin** [comment]
@BillWagner looks like we have some missing images for the nomination committee. Do you want to just use the .NET Bot?

**Comment by BillWagner** [comment]
> @BillWagner looks like we have some missing images for the nomination committee. Do you want to just use the .NET Bot?

Yes, let's use .NET Bot

**Comment by isaacrlevin** [comment]
@BillWagner let me know how this looks, I will merge if you approve

https://jolly-grass-05beb181e-1177.westus2.azurestaticapps.net/about/election

**Comment by BillWagner** [comment]
Thanks @isaacrlevin 

This all looks perfect.  Let's merge and publish.

**Pull request merged**
