### PR TITLE
Project Spotlight

### PR DESCRIPTION
**Pull request by isaacrlevin**
## Task Lists

- [x] Initial UI Design
- [x] Incorporate UI Feedback
- [x] Integrate Api/Function to Get Open Help Wanted Issues
- [ ] Whatever Else?

### CODE REVIEW

**Comment by BethMassi** [comment]
Is there a staging site I can go to and look or do I have to build the site locally?

**Comment by isaacrlevin** [comment]
Looks like we are out of slots. I will deploy a standalone and post the link here

**Comment by clairernovotny** [comment]
Unfortunately Azure Static Sites only supports a single slot; as soon as they support more, we'll be on the plan that gives us that.

**Comment by isaacrlevin** [comment]
@BethMassi I forked the website and deployed my changes, they are here

https://purple-beach-0c9a3421e.azurestaticapps.net/projects/spotlight

**Comment by BethMassi** [comment]
Cool. Great start. I think I'd move the "Get Involved" section to the top and then put the project description under it so it doesn't look like a wall of text. Also, is there a way we can tighten up all the whitespace? There's so much wasted space on the pages. Thanks for doing this!!

**Comment by isaacrlevin** [comment]
This is a trend throughout the site, which can be fixed but would require taking a look at all the pages to make sure they still look good

**Comment by isaacrlevin** [comment]
@clairernovotny was there a plan for a site refresh soon? Wondering if I should just skip the margin conversation.

**Comment by clairernovotny** [comment]
Not sure what you mean by site refresh? Folks have been tweaking/fixing style stuff but there's no major changes currently planned.

**Comment by isaacrlevin** [comment]
Final Version
https://purple-beach-0c9a3421e.azurestaticapps.net/projects/spotlight

@clairernovotny @BethMassi

**Pull request merged**
