### PR TITLE
Create harishchandra-ukirade.md

### PR DESCRIPTION
**Pull request by HarishUkirade**
Initial pull request with speakers directory

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=638) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=638) before we can accept your contribution.<br/><br/>:x: HarishUkirade [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=638)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=638) it.</sub>

**Comment by SeanKilleen** [comment]
@HarishUkirade don't forget to sign the CLA so this can be merged 👍

**Comment by HarishUkirade** [comment]
Please approve review

**Comment by HarishUkirade** [comment]
Hi SeanKilleen,

CLA has been signed, please proceed to merge.

**Pull request merged**
