### PR TITLE
Update policy as per board vote and nominating committee recommendations

### PR DESCRIPTION
**Pull request by clairernovotny**
Recommendations from the Nominating Committee and approved by the board.

### CODE REVIEW

**Comment by benaadams** [comment]
Should this page be updated also? https://dotnetfoundation.org/about/election/campaign

**Comment by clairernovotny** [comment]
Yes...

**Comment by clairernovotny** [comment]
Fixed just now

**Comment by benaadams** [comment]
Also blog post ;) https://dotnetfoundation.org/blog/2020/06/15/net-foundation-election-2020-nominations-open

**Pull request merged**
