### PR TITLE
Speaker directory

### PR DESCRIPTION
**Pull request by daveaglick**
This is the big one, ready for publishing. A few notes:

- I've commented out the navigation in the top nav bar during the soft launch as discussed. We can uncomment it when ready to fully launch.
- I left the speaker profile for Aaron Powell for now just so there's at least one. We can follow-up with him or remove it once we get a few more speaker profiles.
- The site will now need to be periodically rebuilt since we're pulling time-sensitive information like RSS feeds. Nightly should be enough, so we'll want to put it on a GitHub Actions timed trigger.
- You'll need to add an Azure Maps key to enable the speaker map. It should be set as an environment variable `AzureMapsSubscriptionKey` (can also be passed in on the CLI, so let me know if that's easier).

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by clairernovotny** [comment]
Where do we get `AzureMapsSubscriptionKey` from? If you get it to me offline, I can add it as a secret for the actions to use.

**Comment by daveaglick** [comment]
@clairernovotny I used my personal key for testing, which for obvious reasons I'd prefer not to have up on the actual DNF website. You create an Azure Maps Account in Azure and then the key is on the Authentication tab:

image

**Comment by daveaglick** [comment]
Yeah - as far as I know, now that the secret is added (and flowed through as an environment variable?) we just need to trigger a regular build. And we could even skip the timed trigger for now while sorting everything out and getting it merged. The only downside is the blog posts on speaker pages will get out of date until the next build.

**Comment by clairernovotny** [comment]
Secrets are not set as env variables automatically. 

You'd need to set it like this... 
https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables

`${{ secrets.GITHUB_TOKEN }}`

**Comment by daveaglick** [comment]
@clairernovotny I've updated the PR to include passing the maps key secret through to environment variables for the build.

**Comment by isaacrlevin** [comment]
@daveaglick FYI, you need to update the header to show the new speakers page. It isn't there now

image

**Comment by daveaglick** [comment]
@isaacrlevin yep, that's a conscious omission while the directory is in "soft-launch" and we work out the bugs 😃

**Pull request merged**
