### PR TITLE
remove misleading independence claim

### PR DESCRIPTION
**Pull request by matkoniecz**
It is not wrong or surprising that Microsoft has broad veto rights in foundation they setup, but describing this foundation as "Independent" is highly misleading

See https://github.com/dotnet-foundation/Home/discussions/60 for overview why independence claim is misleading at best and https://github.com/dotnet-foundation/Home/discussions/63#discussioncomment-1520898 for the shortened version

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1098) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1098) before we can accept your contribution.<br/><br/>:x: matkoniecz [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=1098)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=1098) it.</sub>

**Comment by isaacrlevin** [comment]
Hey there @matkoniecz,

The claim of independence is based on the legal status of the .NET Foundation entity and how it operates a 501(c)(6) organization. It has nothing to do with the current relationship the Foundation may have with any of its corporate sponsors. 

If you want to get further involved in the foundation, we highly encourage you to join one of your committees and learn more about how the foundation operates. Here is more information on the committees. 

https://dotnetfoundation.org/community/committees

Thanks,

Isaac Levin
Chair of Marketing Committee

**Comment by matkoniecz** [comment]
If you wanted to make narrow claim then mentioning "501(c)(6) organization" would be a better fit.

Claiming that Dotnet foundation is independent while it is fully controlled by Microsoft as far as making important decisions goes is highly misleading.

Also, there is nothing inherently bad in Microsoft making Microsoft-controlled foundation. But claiming that actual situation is different is just raising questions what else stated there is misleading.

**Comment by AraHaan** [comment]
I mean if I was Microsoft making 95% of the things in the foundation you would probably understand where they are all coming from.

**Comment by rprouse** [comment]
@matkoniecz in my six months on the board, I have seen no influence from Microsoft on any decisions made by the foundation. Microsoft donated the .NET Framework and many projects to the Foundation, it is only natural that they want to be able to ensure that those projects continue to be maintained in an open manner. IMHO, Microsoft's best interests are served by a strong and vibrant opensource community.

**Comment by wastaz** [comment]
@isaacrlevin While you may be "technically" right I think as a head of the marketing committee you should understand that peoples interpretation of a word doesnt always align with "technicalities" and this can very much cause marketing to sound false and misleading. In this case, having a dotnet foundation, dotnet being what it is. The word "independent" will not in any way associate with  "its a 501(c)(6) organization" in peoples mind. The immediate association will be "Oh! It's independent from microsoft!". Given the history of .net this is _literally the only real immediate association one can make_ when seeing that byline.

Later recognizing that not only does MS have broad veto rights, the head of the foundation has always been a microsoft employee and probably always will be that...it creates quite the dissonance and the "Wow, thats some false and misleading advertisement"-feeling. And no "Oh but technically, legally since we are..." is going to make that feeling any less bad. 

It really is in the dotnet foundations best interest to be open and trustworthy especially when it comes to these points. As such, as the head of marketing, I would really expect you to be first in line to want to ensure that this type of unclear language and terms is not used in marketing the organization.

**Comment by matkoniecz** [comment]
> I have seen no influence from Microsoft on any decisions made by the foundation

But it is not changing that Microsoft has very broad veto rights, baked into bylaws. As result it is not independent at all.

Even if that "no influence" is 100% true and we ignore that Microsoft definitely took care to ensure that foundation is controlled by people aligned with what Microsoft wants, maybe even Microsoft employees...

**Comment by ddskier** [comment]
I'm DeeDee Walsh and I'm a member of the marketing committee serving with Isaac. I love this input! I agree with what you're saying... We're very tied to Microsoft (which I think a lot of us believe is a good thing) but it feels disingenuous to talk about "independence". These are all issues we have been grappling with for a while - and of course, we're a committee of volunteers... Anyway, I don't have a good answer for you but I love that you're pushing us on this. The main reason I don't want to water down "independence" is that I really really WANT us to be independent and self-sufficient which I know is not the same as actually being independent.

**Pull request closed without merging**
