### PR TITLE
Remove commented sections in Generator.csproj

### PR DESCRIPTION
**Pull request by MeladKamari**
Remove commented sections in Generator.csproj

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=679) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=679) before we can accept your contribution.<br/><br/>:x: MeladKamari [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=679)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=679) it.</sub>

**Comment by MeladKamari** [comment]
All CLA requirements Accepted

**Review by Arhell — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Comment by clairernovotny** [comment]
Closing as I leave this to @daveaglick. I assume this is here to make it easier for him to debug things.

**Comment by daveaglick** [comment]
Correct. We can certainly remove it if it really bothers anyone, but it does make it much easier for me to test and integrate new versions of Statiq with the DNF site. I can add a comment to that effect the next time I'm in here.

**Pull request closed without merging**
