### PR TITLE
Added Joel Hulen speaker profile

### PR DESCRIPTION
**Pull request by joelhulen**
Added my speaker profile.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=373) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=373) before we can accept your contribution.<br/><br/>:x: joelhulen [sign now](https://cla.dotnetfoundation.org/dotnet-foundation/website?pullRequest=373)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-foundation/website?pullRequest=373) it.</sub>

**Review by Arhell — APPROVED** [review]

**Comment by daveaglick** [comment]
Hi @joelhulen - you beat me to it and got in one of the first speaker profiles! In the final version of the speaker directory some of the front matter changed a bit from the earlier submission process. Would you mind updating the front matter in your profile to:

```
Title: Joel Hulen
Location: Virginia Beach, Virginia, United States
Tags:
  - Big Data
  - Artificial Intelligence
  - Serverless
  - Data
GitHub: https://github.com/joelhulen/
LinkedIn: https://www.linkedin.com/in/joel-hulen-ba76b73/
```

Note the tag changes - there's now an "accepted" list of tags here: https://github.com/dotnet-foundation/website/blob/bee2b82d049375f8f6787c17276cebb34c7d513a/Analyzers/ValidateSpeakerTopics.cs - it can be expanded, so let me know if we're missing any that should be covered.

Thanks!

**Comment by joelhulen** [comment]
@daveaglick I've updated as requested. I would suggest adding `Data Engineering` and `Data Science` to the approved list of tags. Thanks!

**Comment by daveaglick** [comment]
Thanks!

@JaySing @clairernovotny - we'll likely need to come up with a process to approve new topic tags.

**Pull request merged**
