### PR TITLE
convert to ?: operator

### PR DESCRIPTION
**Pull request by mokarchi**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sing CLA

**Comment by mokarchi** [comment]
> Please sing CLA

How can I get this license?

**Comment by Arhell** [comment]
try
https://cla.dotnetfoundation.org/

**Comment by mokarchi** [comment]
Untitled

I don't know that why license/cla in this repository dosen't approved!

**Comment by mokarchi** [comment]
I wanna try to get cla license

**Comment by mokarchi** [comment]
@Arhell I submitted a new PRs #1090 and the CLA license was successful

**Pull request closed without merging**
